### PR TITLE
Fixed total infected/deceased count for Poland

### PR DESCRIPTION
**Pull request by dex1g**
Fixed the total infected/deceased numbers for Poland as @zpelechova requested in #264 
They were missing because of recent change in field names on gov.pl

### CODE REVIEW

**Comment by zpelechova** [comment]
Thanks a lot, done! What is the app you are using it for? Just curious ;)

**Comment by dex1g** [comment]
We have an university project to create a web + mobile app that has to be something connected with medicine. We decided to create a PWA application that displays the covid stats on a cool map component that @LeszekBlazewski made, presents stats about user selected regions in a convenient way and also allows users to define which regions they want to receive alerts for, when the infected/deceased count reach certain user defined thresholds. We were really concerned when we realized today that it stopped working, because we have to do a showcase tomorrow. 😅

**Comment by LeszekBlazewski** [comment]
Yup, cheers for the merges 😃  ! Works as expected 👅 

image

Quick preview, sadly not much time to make it super slick but should do 🤖

**Comment by zpelechova** [comment]
Guys, thats super cool! Glad I was online ang could merge right away! Godd luck with your presentation!

**Pull request merged**
